package CodeDeLaRoute;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
//       HomeForm home = new HomeForm(theme);
//       home.getForm().show();
//       NiveauUn un = new NiveauUn(theme);
//       un.getNiveauUn().show();
//        NiveauDeux deux = new NiveauDeux(theme);
//        deux.getNiveauDeux().show();
//        InsertTest test = new InsertTest(theme);
//        test.getForm().show();
//        GererTests test = new GererTests(theme);
//        test.getForm().show();
       Clock s1 = new Clock(theme);
//        ChartForm demos = new ChartForm();
//        current = demos;
//        demos.show(); 
//        mesTests testmodif = new mesTests();
//        ModifierTest t =new ModifierTest(theme, testmodif);
//                t.getForm().show();
       
       
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
