package com.mycompany.myapp;

import Annonces.modeles.Annonces;
import Annonces.modeles.User;
import Annonces.services.Acceuil;
import Annonces.services.ActivityMain;
import Annonces.services.ListAnnonces;
import Annonces.services.Note;
import CodeDeLaRoute.Clock;
import Offres.Accueil;
import Offres.TouteLesOffres;
import com.codename1.components.ImageViewer;
import com.codename1.components.SpanLabel;
import com.codename1.db.Database;
import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.io.Util;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.Button;
import com.codename1.ui.ComboBox;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.Image;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.URLImage;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;



/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current,list,modifier;
    private Resources theme_1,theme;
    
            ArrayList<Annonces> listEtudiants = new ArrayList<>();
                  public static  Database db;

    boolean exist;
            


    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
       Map<String, String> v = theme.getL10N("strings", L10NManager.getInstance().getLanguage());
        if(v == null) {
            v = theme.getL10N("strings", "en");
        }
        UIManager.getInstance().setBundle(v);
        
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        Log.bindCrashProtection(true);
        
        Util.register("Note", Note.class);
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start(){
    
            exist = Database.exists("note");

        try {
            db = Database.openOrCreate("note");

            if (!exist) {
                db.execute("create table note(id INTEGER PRIMARY KEY, titre text, descripition text, id_annonce INTEGER);");
            }

        } catch (IOException ex) {
            //Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      
            //new ListAnnonces(theme).show();
//  Clock s1 = new Clock(theme);
  
new Acceuil(theme).show();
       
           // Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
